import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Home from "./page";
import { AuthProvider } from "../../../legacy/app/components/context/AuthContext";


const inter = Inter({ subsets: ["latin"] });;

export const metadata: Metadata = {
  title: "Dashbord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className="flex">
     <Home/>
      <>
        {children}
      </>
        </body>
        </AuthProvider>
    </html>
  );
}
