import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Footer/page";
import HomePage from "./page";
import { AuthProvider } from "./components/context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Buy sell ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <AuthProvider>
      <body className={inter.className}>
      <HomePage/>
        {children}
      <Footer/>
        </body>
      </AuthProvider>
    </html>
  );
}
